### ISSUE TITLE
keeps saying cant open folder because it has system files

### ISSUE THREAD

**Issue by InactiveCoyote** [hazre/neosvr-mod-manager#21]
![Screenshot 2023-03-06 204016](https://user-images.githubusercontent.com/51268370/223306279-eb4e0c8b-ad8f-4e29-ae80-cad719e1505e.png)

i tried this with chrome and edge

**Comment by hazre** [comment]
Due to security reasons in the browser, you have to create junction link to your Neos installation folder.

Doing this allows the browser to access the folder from a form of shortcut rather than access the directory directly, bypassing the restriction and allowing access to your Neos installation folder.

You can do this under windows like this for example: (I like putting mine in the Documents directory)
`mklink /J "C:\Users\username\Documents\NeosVR" "C:\Program Files (x86)\Steam\steamapps\common\NeosVR"`
