### ISSUE TITLE
[Feature Request] Decouple filesystem access from listing mods

### ISSUE THREAD

**Issue by ljoonal** [hazre/neosvr-mod-manager#6]
I don't see why listing all the mods & the search couldn't be made to work with any device. I'm guessing it was easier to do for the initial implementation, but the "unsupported browser" dialog is a shame since I think this could offer most of the functionality even on browsers that don't support the FS APIs. 

I personally would additionally like to just replace the current web mod list at [neosmodloader.com/mods](https://www.neosmodloader.com/mods.html) with this. But that'd require for this to be able to at least list the mods with most browsers, as the higher priority on that is listing the mods in a way that works for most people 😛

Additionally decoupling & abstracting the filesystem access from the rest of the logic could help in the future with other use cases. For example I did think about seeing if this could be packaged with https://tauri.app/ for example, so that people wouldn't need to install chromium just to use this 😄 But that'd use tauri's events/messages instead of JS for the FS access (and also do the same for the non-CORS request instead of requiring an API server), so currently doing that would require replacing a lot of the JS code in a way which I don't think would be too easy to maintain with the current codebase.

**Comment by hazre** [comment]
Funny enough, my original POC had was decoupled from the mods list and loading local mods but I choose to simply it to lessen the confusion. I will definitely explore it again.

Yeah I've had Tauri in my mind for a bit. I've looked into the Sveltekit process and it seems very easy to do. I just don't have any rust knowledge to rewrite the FS part on the rust. I actually messaged @zkxs about this since they've attempted to create mod updater before in rust, not too sure if they're interested to help out though.
